name: Coin Backend CI/CD Deployment

on:
  push:
    branches:
      - main

env:
  PROJECT_DIR: 2025_PhyoNyiNyiPaing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ${{ env.PROJECT_DIR }}/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: terraform init

      - name: Terraform Apply (auto-approve)
        working-directory: ${{ env.PROJECT_DIR }}/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_public_key: ${{ secrets.EC2_PUBLIC_KEY }}
        run: terraform apply -auto-approve

      - name: Get EC2 Public IP from Terraform output
        id: tfoutput
        working-directory: ${{ env.PROJECT_DIR }}/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_public_key: ${{ secrets.EC2_PUBLIC_KEY }}

        run: |
          EC2_IP=$(terraform output -raw ec2_public_ip | grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
          echo "Extracted EC2 IP: $EC2_IP" >&2
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.PROJECT_DIR }}
          file: ${{ env.PROJECT_DIR }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/coin-challenge-backend:latest

      - name: Write private key to file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run Ansible to deploy container
        run: |
          sudo apt-get update && sudo apt-get install -y ansible
          ansible-playbook ${{ env.PROJECT_DIR }}/ansible/playbook.yml \
            -i "$EC2_IP," \
            --private-key key.pem \
            -u ${{ secrets.EC2_USER }} \
            -e "docker_username=${{ secrets.DOCKERHUB_USERNAME }}"
